export enum MutationTypes {
    REGISTER = 'REGISTER',
    LOGIN = 'LOGIN',
    LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE',
    LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK',
    SET_LOGGED_IN = 'SET_LOGGED_IN',
    SET_USER = 'SET_USER',
    SIGN_OUT = 'SIGN_OUT',
    GET_ERROR = 'GET_ERROR',
}

export enum ActionTypes {
    REGISTER = 'REGISTER',
    FETCH_USER = 'FETCH_USER',
    LOGIN = 'LOGIN',
    LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE',
    LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK',
    SIGN_OUT = 'SIGN_OUT',
}